export const world = {
  phase: 'menu',
  playerPosition: { x: 0, y: 1.8, z: 0 },
  isDay: true,
  dayNightProgress: 0,
  wildPokemon: [],
  stones: [],
  battleTargetId: null,
  money: 0,
  exp: 0,
  difficulty: 'easy',
  treasureChests: [],
  isAdmin: false,
  flying: false,
  speedBoost: false,
  superJump: false,
  buildMode: false,
  buildObjectType: 'tree',
  builtObjects: [],
  playerDirection: { x: 0, y: 0, z: -1 },
  rainbowActive: false,
  damageDodge: false,
  playerData: null,
};